const express=require("express")
const cookieParser=require('cookie-parser')
const app=express()
const authRouter=require('./routes/auth.routes')
const accountRouter=require('./routes/account.routes')
const transactonRouter=require('./routes/account.routes')
app.use(express.json())
app.use(cookieParser())
app.use('/api/auth',authRouter)
app.use('/api/accounts',accountRouter)
app.use('/api/transactions',transactonRouter)
module.exports=app